EZP-31462: Removed password hash types break login
ezsystems/ezplatform-kernel pull request #141
Opened 2020-12-02 12:21 UTC by glye

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | EZP-31462
| **Type**                                   | bug
| **Target eZ Platform version** | `v3.1`
| **BC breaks**                          | no
| **Doc needed**                       | maybe?

The previous fixes are incomplete. When an invalid hash type is detected, we expire the password and ask the user to enter a new password. But when we save this new password, we don't update the hash type, which means the password isn't saved, and the user ends up in a redirect loop.

This fix catches when the type is invalid, and sets it to the default type in that case.

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [ ] Provided automated test coverage.
- [x] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [ ] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [ ] Asked for a review (ping `@ezsystems/php-dev-team`).

2020-12-03 09:50 UTC, glye commented
Fixup: Get the default hash type from the password hash service, rather than hardcoding it.

NB: It's not at all certain that the final fix will look like this. It may be the wrong place to fix it.

2020-12-04 08:47 UTC, alongosz requested changes
Could be, but I'm not gonna accept this w/o either integration or unit tests.

2020-12-08 12:41 UTC, glye commented
Fair point. Set as work in progress, and I've asked for Eng help on it. I need to focus on the growing security issue list, and this isn't security. Maybe @kaff will be able to look at this later?  🏃💨

2021-02-11 01:16 UTC, alongosz approved these changes

2021-02-11 07:00 UTC, Steveb-p approved these changes

2021-02-11 07:00 UTC, Steveb-p commented on eZ/Publish/Core/Repository/UserService.php
> +     * @return \eZ\Publish\API\Repository\Values\User\User
nitpick: Unnecessary `@return` declaration - it matches the method's return type afaik.

2021-02-11 07:30 UTC, adamwojs approved these changes

2021-02-11 08:06 UTC, ciastektk approved these changes

2021-02-16 09:55 UTC, micszo approved these changes
Retested successfully.
QA Approved on Ibexa Experience v3.2.4 with diff.

2021-02-16 11:03 UTC, merged