EZP-31795: Introduced proxy objects for content thumbnails
ezsystems/ezplatform-kernel pull request #157
Opened 2021-01-11 11:24 UTC by ViniTou

YOUR PR WILL ONLY BE HANDLED IF YOU EDIT THIS DESCRIPTION AND FOLLOW THE CHECKLIST BELOW. THEN, REMOVE THIS LINE.

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | EZP-31795
| **Type**                                   | improvement
| **Target eZ Platform version** | `v3.2`
| **BC breaks**                          | no
| **Doc needed**                       | no

#### Checklist:
- [ ] Provided PR description.
- [ ] Tested the solution manually.
- [ ] Provided automated test coverage.
- [ ] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [ ] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [ ] Asked for a review (ping `@ezsystems/php-dev-team`).

2021-01-11 13:57 UTC, Nattfarinn approved these changes

2021-01-11 15:24 UTC, lserwatka approved these changes

2021-01-11 15:26 UTC, Steveb-p approved these changes

2021-01-11 15:26 UTC, Steveb-p commented on eZ/Publish/Core/FieldType/Image/ImageThumbnailProxyStrategy.php
> +class ImageThumbnailProxyStrategy implements FieldTypeBasedThumbnailStrategy
Nitpick
```suggestion
final class ImageThumbnailProxyStrategy implements FieldTypeBasedThumbnailStrategy
```

2021-01-12 12:04 UTC, micszo approved these changes
QA Approved with image, image asset sanities on Ibexa Commerce 3.2.3-dev and Ibexa Experience v3.2.3 with diff.

2021-01-12 17:53 UTC, adamwojs requested changes
+1 but you need add `\eZ\Publish\API\Repository\Values\Content\Thumbnail` to `\eZ\Bundle\EzPublishCoreBundle\Cache\Warmer\ProxyCacheWarmer::PROXY_CLASSES` See https://github.com/ezsystems/ezpublish-kernel/pull/2844 for more details.

2021-01-12 18:37 UTC, lserwatka commented
@ViniTou we need to address it.

2021-01-13 08:18 UTC, adamwojs approved these changes

2021-01-13 09:24 UTC, merged

2021-01-13 09:24 UTC, lserwatka commented
@ViniTou could you merge it up?