Patch 1
ezsystems/ezplatform-kernel pull request #202
Opened 2021-06-22 07:25 UTC by plozmun

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | EZP-XXXXX
| **Type**                                   | bug
| **Target eZ Platform version** | `v3.2.8`
| **BC breaks**                          | no
| **Doc needed**                       | no

With multilingual options sometimes this cause next error:
```
array_merge() does not accept unknown named parameters
```

#### Checklist:
- [X] Provided PR description.
- [X] Tested the solution manually.
- [ ] Provided automated test coverage.
- [X] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [X] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [ ] Asked for a review (ping `@ezsystems/php-dev-team`).

2021-06-23 11:23 UTC, alongosz approved these changes
Looks like this can be covered easily by some unit test.

2021-06-25 13:19 UTC, Steveb-p approved these changes

2021-06-25 13:58 UTC, alongosz requested changes
@plozmun to move forward with this fix we need a [JIRA issue](https://issues.ibexa.co/) with detailed steps to reproduce, so we can send this to our QA Team for testing.

2021-06-25 15:52 UTC, plozmun commented
> @plozmun to move forward with this fix we need a [JIRA issue](https://issues.ibexa.co/) with detailed steps to reproduce, so we can send this to our QA Team for testing.

Yes, of course, I'll create an issue and try to make a unit test for this

2021-06-25 18:01 UTC, Steveb-p commented
@plozmun btw, it's a PHP8-only issue I presume? Since it relates to named parameters?

2021-08-02 11:46 UTC, closed without merging