[WIP] IBX-605: Refactored and optimized orphaned URLs deleting
ezsystems/ezplatform-kernel pull request #205
Opened 2021-06-28 16:14 UTC by barw4

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-605](https://issues.ibexa.co/browse/IBX-605)
| **Type**                                   | improvement
| **Target eZ Platform version** | `v3.3`
| **BC breaks**                          | no
| **Doc needed**                       | no

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [ ] Provided automated test coverage.
- [x] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [x] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [ ] Asked for a review (ping `@ezsystems/php-dev-team`).

2021-07-07 05:51 UTC, adamwojs approved these changes

2021-07-07 05:51 UTC, adamwojs commented on eZ/Publish/Core/FieldType/Url/UrlStorage/Gateway/DoctrineStorage.php
> +    private function deleteOrphanedUrls(array $potentiallyOrphanedUrls): void
`@param int[] $potentiallyOrphanedUrls` is missing

2021-07-07 14:28 UTC, alongosz requested changes

2021-07-07 14:28 UTC, alongosz commented on eZ/Publish/Core/FieldType/Url/UrlStorage/Gateway/DoctrineStorage.php
> +                $selectQuery->expr()->andX(
Technical debt: method `andX` is deprecated.

2021-07-07 14:28 UTC, alongosz commented on eZ/Publish/Core/FieldType/Url/UrlStorage/Gateway/DoctrineStorage.php
> +                $selectQuery->expr()->andX(
Why would you use `$selectQuery` expressions inside `$deleteQuery`? The expression builder is the same, but semantically it does not make sense to me.

2021-07-07 14:28 UTC, alongosz commented on eZ/Publish/Core/FieldType/Url/UrlStorage/Gateway/DoctrineStorage.php
> +        $potentiallyOrphanedUrls = $statement->fetchAll(PDO::FETCH_COLUMN);
Technical debt:
> Method fetchAll is deprecated. Use fetchAllNumeric(), fetchAllAssociative() or fetchFirstColumn() instead.

2021-07-19 08:57 UTC, alongosz approved these changes

2021-07-20 14:27 UTC, piotrbisaga commented
QA approved.
Check on Ibexa Commerce 3.3.6 on branch.

2021-07-21 07:02 UTC, merged

2021-07-21 07:02 UTC, lserwatka commented
You can merge it up now

2021-07-21 11:46 UTC, adamwojs commented
Done.