IBX-175: Fixed invalid VersionValidator errors output when validation fails for multilingual content
ezsystems/ezplatform-kernel pull request #213
Opened 2021-07-14 12:52 UTC by konradoboza

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-175](https://issues.ibexa.co/browse/IBX-175)
| **Type**                                   |bug
| **Target eZ Platform version** | `v3.3`
| **BC breaks**                          | no
| **Doc needed**                       | no

Due to the missing `$language` option, while fetching fields to be validated, we end up with a validation error for each content translation, regardless of field value's correctness.

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [ ] Provided automated test coverage.
- [x] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [x] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [x] Asked for a review (ping `@ezsystems/php-dev-team`).

2021-07-19 06:52 UTC, ViniTou approved these changes

2021-07-19 08:11 UTC, adamwojs approved these changes

2021-07-19 08:54 UTC, alongosz requested changes
Looks like this case can be covered either with an integration test[1] or a unit test.

[1] Seems simpler given the complexity of Validator itself

2021-07-21 13:04 UTC, alongosz approved these changes

2021-07-22 10:41 UTC, tomaszszopinski approved these changes
QA approved on IbexaDXP 3.3.6 & 3.3.6-dev with diff & patch.

2021-07-22 10:42 UTC, konradoboza commented
@alongosz could you please merge?

2021-07-22 10:46 UTC, merged

2021-07-22 10:47 UTC, alongosz commented
@konradoboza you can merge it up

2021-07-22 10:59 UTC, konradoboza commented
Done in https://github.com/ezsystems/ezplatform-kernel/commit/389373b8388e7af011b2822fecff3658c6b372b3.