IBX-704: Added LocationChildrenTermAggregation
ezsystems/ezplatform-kernel pull request #215
Opened 2021-07-19 09:17 UTC by mateuszbieniek

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | https://issues.ibexa.co/browse/IBX-704
| **Type**                                   | improvement
| **Target eZ Platform version** | `v3.2`
| **BC breaks**                          | no
| **Doc needed**                       | no

This is the kernel part for https://github.com/ezsystems/ezplatform-admin-ui/pull/1792

2021-07-19 09:18 UTC, mateuszbieniek commented
ping @ezsystems/engineering-team

2021-07-19 09:40 UTC, nkostiv commented
> ping @ezsystems/engineering-team

@mateuszbieniek engineering-team includes also java team. We have separate `@ezsystems/php-dev-team`, `@ezsystems/javascript-dev-team`,` @ezsystems/java-dev-team `

2021-07-19 09:41 UTC, mateuszbieniek commented
> > ping @ezsystems/engineering-team
> 
> @mateuszbieniek engineering-team includes also java team. We have separate `@ezsystems/php-dev-team`, `@ezsystems/javascript-dev-team`,`@ezsystems/java-dev-team`

Awww, my bad - sorry.

2021-07-19 12:45 UTC, adamwojs requested changes

2021-07-19 12:45 UTC, adamwojs commented on eZ/Publish/API/Repository/Values/Content/Query/Aggregation/LocationChildrenTermAggregation.php
> +final class LocationChildrenTermAggregation extends AbstractTermAggregation
Integration tests are missing.

2021-07-23 08:08 UTC, adamwojs requested changes

2021-07-26 09:52 UTC, alongosz approved these changes

2021-07-26 10:16 UTC, adamwojs approved these changes

2021-07-26 10:18 UTC, webhdx approved these changes

2021-07-28 12:26 UTC, bogusez approved these changes

2021-07-29 07:43 UTC, merged

2021-07-29 12:01 UTC, mateuszbieniek commented
Merged up
1.3: https://github.com/ezsystems/ezplatform-kernel/commit/d8d00233c2815ea24e1489b25abc220aac70b342
master: https://github.com/ezsystems/ezplatform-kernel/commit/1945b15ecbb0f008174aaa091ace4faf979e5250