IBX-1308: Added is_system flag to the ContentTypeGroup
ezsystems/ezplatform-kernel pull request #250
Opened 2021-10-22 10:53 UTC by mikadamczyk

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-1308](https://issues.ibexa.co/browse/IBX-1308)
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | no

There is a need to have in our system a system/technical ContentTypeGroup. First, it will be used in a Product Catalog to represent a group where ProductTypes will be stored. Later it could be used as a group for administrator users. A new command is introduced to allow mark an existing group as a system or not system group by executin `ibexa:content-type-group:set-system content-type-group-identifier --system` or `ibexa:content-type-group:set-system content-type-group-identifier --no-system`

By design, this flag only affects fetching a list of ContentTypeGroups. Fetching single group or ContentTypes under group remains unchanged.

As a result of this change, a method ContentTypeService::loadContentTypeGroups will return only groups which are not a system group.

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [x] Provided automated test coverage.
- [x] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [x] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [x] Asked for a review (ping `@ezsystems/engineering-team`).

2021-11-02 08:23 UTC, alongosz requested changes

2021-11-02 08:23 UTC, alongosz commented on composer.json
> +            "Ibexa\\Bundle\\Command\\": "src/bundle/Command",
?
Seems like a wrong placement. This is multi-bundle level.

2021-11-02 09:48 UTC, Steveb-p approved these changes

2021-11-02 15:14 UTC, alongosz approved these changes

2021-11-08 08:41 UTC, kacper-wieczorek-ibexa approved these changes
QA - approved. Given commands set is_system "flag" properly on CTG.

2021-11-09 10:12 UTC, merged

2021-11-09 11:33 UTC, webhdx commented
Can someone from @ezsystems/documentation-team check the naming? 

`ibexa:content-type-group:set-system content-type-group-identifier --system` 
`ibexa:content-type-group:set-system content-type-group-identifier --no-system`

This seems incorrect to me and overcomplicated. How about:
`ibexa:content-type-group:set-system-flag content-type-group-identifier` 
`ibexa:content-type-group:set-system-flag content-type-group-identifier --clear`
?

2021-11-09 12:13 UTC, DominikaK commented
```

2021-11-09 12:20 UTC, mikadamczyk commented
We could make a change but `--no-system` is Symfony standard (https://symfony.com/doc/current/console/input.html) so it should not be confusing. For me, it is something like setSystem true or false

```
InputOption::VALUE_NEGATABLE
    Accept either the flag (e.g. --yell) or its negation (e.g. --no-yell). 
```