IBX-1999: Added countAll function for URLWildcards
ezsystems/ezplatform-kernel pull request #282
Opened 2022-01-25 09:53 UTC by mateuszdebinski

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-1999](https://issues.ibexa.co/browse/IBX-1999)
| **Type**                                   | improvement
| **Target Ibexa version** | `v3.3`
| **BC breaks**                          | no

Related PR: https://github.com/ezsystems/ezplatform-admin-ui/pull/2030

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [ ] Provided automated test coverage.
- [x] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [x] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [x] Asked for a review (ping `@ezsystems/engineering-team`).

2022-01-25 10:47 UTC, Steveb-p approved these changes

2022-01-25 10:47 UTC, Steveb-p commented on eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway/DoctrineDatabase.php
> +            ->select('count(id)')
```suggestion
            ->select('COUNT(id)')
```

or even

```suggestion
            ->select($this->connection->getDatabasePlatform()->getCountExpression('id'))
```

2022-01-25 14:08 UTC, konradoboza approved these changes

2022-01-25 17:12 UTC, adamwojs requested changes
Integration tests are missing. They are mandatory whenever you change PAPI.

2022-01-25 17:28 UTC, adamwojs approved these changes

2022-01-27 14:28 UTC, bogusez approved these changes

2022-01-28 09:29 UTC, merged