IBX-2041: Made LocalAdapter lazy loaded to fix commands having wrong adapter set
ezsystems/ezplatform-kernel pull request #283
Opened 2022-02-03 14:14 UTC by barw4

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-2041](https://issues.ibexa.co/browse/IBX-2041)
| **Type**                                   | bug
| **Target Ibexa version** | `v3.3`
| **BC breaks**                          | no

As the title states. Without this change, all of the console commands that use different `--siteaccess` option other than `default` have wrongly set Site Access because the `ConsoleListener` which changes Site Access is executed **after** the services are set.

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [ ] Provided automated test coverage.
- [x] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [x] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [x] Asked for a review (ping `@ezsystems/engineering-team`).

2022-02-08 12:52 UTC, alongosz reviewed
@barw4 can you give an example of such command? I see steps to reproduce in the ticket, but I need deeper technical analysis of what is happening. Which variable(s) and where are not properly set so the issue occurs?

2022-02-08 12:57 UTC, barw4 commented
sure, you can easily reproduce this by changing some `var_dir` on certain site access and then dumping the root dir here: https://github.com/ezsystems/ezplatform-kernel/blob/1.3/eZ/Publish/Core/IO/Adapter/LocalAdapter.php#L35.

now it's just a matter of running any command with the `--siteaccess=new_site_access` parameter in `prod` environment. You can see that `LocalAdapter` has been constructed before `ConsoleListener` changed the site access from `default` to `new_site_acccess`.

2022-02-08 13:07 UTC, alongosz requested changes
> sure, you can easily reproduce this by changing some var_dir on certain site access and then dumping the root dir here: https://github.com/ezsystems/ezplatform-kernel/blob/1.3/eZ/Publish/Core/IO/Adapter/LocalAdapter.php#L35.

Okay, so there's a bug there, which just got hidden by `lazy`. What needs to be really fixed here is config resolver usage in the constructor. This is incorrect because of the Symfony Container architecture. Refactor please both the class and its parent to lazily fetch both properties, so there are not configResolver calls in the constructor.

This could be achieved by inline-ing the call, but given the batch performance it would be better to use lazy property pattern, sth like:
```php
if (!isset($this->property)) {
    $this->property = $this->configResolver->getParameter('property');
}

return $this->property;
```
You might also need to react to `\eZ\Publish\Core\MVC\Symfony\MVCEvents::CONFIG_SCOPE_CHANGE` event and update those properties in this case.

2022-02-09 09:12 UTC, adamwojs requested changes
Agree with @alongosz

2022-02-11 13:51 UTC, barw4 commented
Closed due to https://issues.ibexa.co/browse/IBX-2295

2022-02-11 13:51 UTC, closed without merging