Expose `getSchemaFiles` & `getFixtures` methods in IbexaTestKernel
ezsystems/ezplatform-kernel pull request #284
Opened 2022-02-08 13:39 UTC by Steveb-p

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | N/A
| **Type**                                   | improvement
| **Target Ibexa version** | `v3.3`
| **BC breaks**                          | no

This PR is extracted from #242.

It exposes `getSchemaFiles` and `getFixtures` as methods in `IbexaTestKernel`, so that bootstrapping scripts can make use of these.

Previously the only location these were available were `IbexaKernelTestCase`, which meant that they were only accessible during test execution itself.

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [x] Provided automated test coverage.
- [x] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [x] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [x] Asked for a review (ping `@ezsystems/engineering-team`).

2022-02-08 17:00 UTC, alongosz requested changes
@Steveb-p CI is failing here

2022-02-08 19:47 UTC, Steveb-p commented
> @Steveb-p CI is failing here

Fixed. Apparently it's a new "feature" in php-cs-fixer 3.6.0.

> minor https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6199 HeaderCommentFixer - support monolithic files with shebang (kubawerlos, keradus)

2022-02-09 09:58 UTC, alongosz approved these changes

2022-02-10 10:16 UTC, adamwojs approved these changes

2022-02-10 10:23 UTC, webhdx approved these changes

2022-02-10 10:24 UTC, konradoboza approved these changes

2022-02-10 10:28 UTC, merged

2022-02-10 10:54 UTC, Steveb-p commented
Merged into `main` in [6d60013a](https://github.com/ibexa/core/commit/6d60013a8377afa900a10dee16516e056cbc1524).