IBX-1090: Fixed calculations and displaying of ezdate FT, as it should always be represented in UTC
ezsystems/ezplatform-kernel pull request #285
Opened 2022-02-09 09:36 UTC by ViniTou

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-1090](https://issues.ibexa.co/browse/IBX-1090)
| **Type**                                   | bug
| **Target Ibexa version** | `v3.3`
| **BC breaks**                          | no

Reverted previous changes in this area, as date without meaningful time should always be represented in UTC.

#### Checklist:
- [ ] Provided PR description.
- [ ] Tested the solution manually.
- [ ] Provided automated test coverage.
- [ ] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [ ] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [ ] Asked for a review (ping `@ezsystems/engineering-team`).

2022-02-09 09:41 UTC, Steveb-p approved these changes
Code style issue (coming from newly released php-cs-fixer 3.6.0) can be fixed separately.

2022-02-09 11:39 UTC, alongosz approved these changes

2022-02-10 13:18 UTC, adamwojs approved these changes

2022-02-11 13:36 UTC, micszo requested changes
Edit and view mode in admin display the same date.

However frontend now displays a day behind.

![Screenshot 2022-02-11 at 14 33 39](https://user-images.githubusercontent.com/13622502/153600609-e3d9d1a3-b5f3-4e27-8e5c-1620a5710780.png)

![Screenshot 2022-02-11 at 14 33 49](https://user-images.githubusercontent.com/13622502/153600630-08e2ba74-c6f2-4150-b98a-47dc095de13f.png)

Testing on Ibexa Commerce 3.3.15-dev with branches in prod env.

2022-02-11 13:44 UTC, micszo commented
(without the fix frontend and edit mode display the same date and view mode is a day behind)

2022-02-11 13:47 UTC, micszo commented
(set "America/Sao_Paulo" in php.ini and "America/Vancouver" in back-office)

2022-02-14 08:55 UTC, ViniTou commented
@micszo 
It seems there is a difference how FT blocks are resolved between 3.3 and 4.0 and thats needs to be investigated in separate ticket.
anyway, here is the same fix (+datetime) for 3.3 commerce
https://github.com/ezsystems/ezcommerce-base-design/pull/51

2022-02-14 08:57 UTC, micszo commented
Thanks - checking!

2022-02-16 12:29 UTC, micszo approved these changes
QA Approved on Ibexa Commerce 3.3.15-dev with branches. Diffs load cleanly on v3.3.14.

2022-02-16 12:48 UTC, merged