IBX-2870: Implemented ImageAssetMapper strategy needed for DAM and GraphQL synchronization
ezsystems/ezplatform-kernel pull request #313
Opened 2022-06-01 14:27 UTC by barw4

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-2870](https://issues.ibexa.co/browse/IBX-2870)
| **Type**                                   | improvement
| **Target Ibexa version** | `v3.3`
| **BC breaks**                          | no

Related PRs:
-
- 

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [ ] Provided automated test coverage.
- [x] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [x] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [x] Asked for a review (ping `@ezsystems/engineering-team`).

2022-06-02 14:31 UTC, ViniTou commented on src/lib/FieldType/ImageAsset/ImageAssetMapperStrategyInterface.php
> +interface ImageAssetMapperStrategyInterface
I wonder if that interface & impl should not be part of graphql instead of kernel/core.

@alongosz @adamwojs

2022-06-02 14:35 UTC, barw4 commented on src/lib/FieldType/ImageAsset/ImageAssetMapperStrategyInterface.php
> +interface ImageAssetMapperStrategyInterface
I was thinking about this initially but that would mean that the GraphQL bundle would be required in DAM bundle which is not the case for now.

2022-06-02 14:47 UTC, alongosz commented on src/lib/FieldType/ImageAsset/ImageAssetMapperStrategyInterface.php
> +interface ImageAssetMapperStrategyInterface
It depends on what it's meant for - I mean where, how and what for you use this service.
Code-wise looks self-contained, but not used. 
I need broader context here.

2022-06-02 14:48 UTC, alongosz requested changes
If this is dangling implementation without usage, we MUST have some test coverage, at least unit with mocked Content, or integration for simplicity.

2022-06-02 14:48 UTC, alongosz commented on eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
> +            - { name: ibexa.fieldtype.image_asset.mapper_strategy, priority: 0 }
naming:
```suggestion
            - { name: ibexa.field_type.image_asset.mapper.strategy, priority: 0 }
```

2022-06-03 07:13 UTC, ViniTou commented on src/lib/FieldType/ImageAsset/ImageAssetMapperStrategyInterface.php
> +interface ImageAssetMapperStrategyInterface
Tbh, I do not see problem with DAM having dependency on graphql, as the only reason for this is to provide DAM assets in graphql response

2022-06-03 13:53 UTC, barw4 commented
Closed in favor of https://github.com/ezsystems/ezplatform-graphql/pull/126

2022-06-03 13:53 UTC, closed without merging