IBX-1119: Implemented Site Access listener for IO requests
ezsystems/ezplatform-kernel pull request #317
Opened 2022-07-01 10:03 UTC by barw4

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-1119](https://issues.ibexa.co/browse/IBX-1119)
| **Type**                                   |bug
| **Target Ibexa version** | `v3.3`
| **BC breaks**                          | no

Injecting a SiteAccess allows for proper resolution of a repository, and hence, a `var_dir`.

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [x] Provided automated test coverage.
- [x] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [x] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [x]  Asked for a review (ping `@ezsystems/engineering-team`).

2022-07-04 08:07 UTC, alongosz requested changes

2022-07-04 08:07 UTC, alongosz commented on eZ/Bundle/EzPublishIOBundle/Resources/config/io.yml
> +            - '%ezpublish.siteaccess.list%'
It would be better here to use named parameters. More flexible.

2022-07-04 08:07 UTC, alongosz commented on src/bundle/IO/EventListener/StreamFileSiteAccessListener.php
> +        foreach ($this->siteAccessList as $siteAccess) {
Full SiteAccess list is provided by the SiteAccessService (`SiteAccessServiceInterface::getAll`)

2022-07-04 09:15 UTC, adamwojs requested changes
Sorry, but this is wrong direction. 

Executing proposed logic for all available site accesses in every request (there might be hundreds of them since we have site factory) will kill application performance.

2022-07-04 09:18 UTC, barw4 commented
> Sorry, but this is wrong direction.
> 
> Executing proposed logic for all available site accesses in every request (there might be hundreds of them since we have site factory) will kill application performance.

@adamwojs Sure, I agree, however, please let me know how else can we approach this with having only the `localhost/var/repository2/storage/images/image.png` URL.

2022-07-04 09:20 UTC, Steveb-p commented on eZ/Bundle/EzPublishIOBundle/Resources/config/io.yml
> +            - '%ezpublish.siteaccess.list%'
For our own services this is true. Do keep in mind that external services can have their argument names changed, so it's valid to use argument order there (just a side note).

2022-10-04 11:42 UTC, alongosz requested changes
@barw4 given the JIRA description
> When adding manualy the current siteaccess to the request (or a siteaccess using this second repo), the image is correctly served: http://example.com/admin2/var/repo2/storage/images/…

We would rather like you to investigate why generated URI does not include `admin2` component and what can be done to change that. Additionally what would be the BC impact of such change and how can we ensure BC (we were thinking about SA Matcher).

2024-07-09 08:32 UTC, closed without merging