IBX-2634: Added argument to functions to ignore ownership
ezsystems/ezplatform-kernel pull request #321
Opened 2022-07-07 09:45 UTC by mateuszdebinski

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-2634](https://issues.ibexa.co/browse/IBX-2634)
| **Type**                                   | bug/improvement
| **Target Ibexa version** | `v3.3`
| **BC breaks**                          | no

In order not to change the interface and not to cause BC, only the functions have been changed so that you can pass the argument to ignore the owner - the mechanism itself already existed in our product

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [x] Provided automated test coverage.
- [x] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [x] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [x] Asked for a review (ping `@ezsystems/engineering-team`).

2022-07-07 11:09 UTC, alongosz requested changes
AFAIR any change needs to be reflected on an API interface, because we use ProxyManager which won't see them otherwise. But... @adamwojs could you validate that statement? ;)

Question: what is the use case?

2022-07-07 11:33 UTC, mateuszdebinski commented
@alongosz 

If I remember correctly, the API interface change won't go through because of BC.

In migration, we allow setting creatorId or modifierId, if a user does not have the appropriate permissions then we throw an exception. However, I probably went a bit too far, because as I read the ticket now, the client would like that if the user does not exist or does not have permission to create/edit, should be used, default user in migration (admin) or  from --user-context option

2022-07-08 09:00 UTC, alongosz requested changes
It feels to me that this should be fixed in ibexa/migrations.
POV ping @Steveb-p

2022-07-14 09:07 UTC, mateuszdebinski commented
I close this PR as we can do it in the migration bundle itself

2022-07-14 09:07 UTC, closed without merging