IBX-6592: Allowed `Location` to be a part of permission check for Object State assignment
ezsystems/ezplatform-kernel pull request #391
Opened 2023-11-07 16:07 UTC by barw4

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-6592](https://issues.ibexa.co/browse/IBX-6592)
| **Type**                                   |bug
| **Target Ibexa version** | `v3.3`
| **BC breaks**                          | no

#### Checklist:
- [ ] Provided PR description.
- [ ] Tested the solution manually.
- [ ] Provided automated test coverage.
- [ ] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [ ] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [ ] Asked for a review (ping `@ezsystems/engineering-team`).

2023-11-28 08:59 UTC, ViniTou commented
Correct me if I get this wrong.
Now (maybe it also works like this right now, don't know) it will be possible to set global object state just with access to specific subtree? Like what if content is in more then one location?

2023-11-30 12:06 UTC, Nattfarinn requested changes
Changes to `ContentService` interface are not applied to Event layer. Please update `setContentState` method implementation and add new field to `BeforeSetContentStateEvent` and `SetContentStateEvent` events.

2023-11-30 12:17 UTC, Nattfarinn requested changes

2023-11-30 12:17 UTC, Nattfarinn commented on eZ/Publish/API/Repository/ObjectStateService.php
> +        ?Location $location = null
Is it necessary? This Location parameter does not affect method logic and is just workaround for `PermissionResolver`. It is also security risk, as **not** setting this parameter will omit some of limitations checks.

2023-12-01 09:15 UTC, Nattfarinn commented
Related comment: https://github.com/ezsystems/ezplatform-admin-ui/pull/2112#issuecomment-1835737817

2023-12-20 12:08 UTC, closed without merging