LegacyStorageFileRowReader: handle the case when statement->fetch returns false
ezsystems/ezplatform-kernel pull request #89
Opened 2020-07-17 21:09 UTC by SerheyDolgushev

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EZP-31748](https://jira.ez.no/browse/EZP-31748)
| **Type**                                   | bug
| **Target eZ Platform version** | `v3.0.5`, `v3.1.0`
| **BC breaks**                          | no
| **Tests pass**                          | yes
| **Doc needed**                       | no

In some cases `ezplatform:io:migrate-files` command fails because of the following error:
```bash
bin/console ezplatform:io:migrate-files --from=default,default --to=XXX,YYY --no-interaction -vvv

...

In LegacyStorageFileRowReader.php line 45:
 
 [ErrorException] 
 Notice: Trying to access array offset on value of type bool

```
#### Checklist:
- [x] PR description is updated.
- [x] Tests are implemented.
- [x] Added code follows Coding Standards (use `$ composer fix-cs`).
- [x] PR is ready for a review.

2020-09-21 11:33 UTC, kaff approved these changes

2020-09-29 17:16 UTC, alongosz requested changes

2020-09-29 17:16 UTC, alongosz commented on eZ/Bundle/EzPublishIOBundle/Migration/FileLister/FileRowReader/LegacyStorageFileRowReader.php
> +        return is_array($row) ? $this->prependMimeToPath($row['filename'], $row['mime_type']) : null;
This should be more strict, the fetch result can be either array or boolean, so this should be enough:

```suggestion
        return false !== $row ? $this->prependMimeToPath($row['filename'], $row['mime_type']) : null;
```

2020-09-29 17:51 UTC, SerheyDolgushev commented
@alongosz committed your suggestion

2020-09-29 17:56 UTC, alongosz approved these changes

2020-09-29 17:59 UTC, merged

2020-09-29 17:59 UTC, lserwatka commented
@alongosz could you merge it up?

2020-09-29 18:09 UTC, alongosz commented
Merged up to master.

Thank you @SerheyDolgushev :tada: